export const CONFIG = {
  SHEET_ID: "1MjCExw6iwjcr0ubYgUdklIsWL_3IXn14hSE5qIXpGI4",
  API_KEY: "AIzaSyAu5Ka6OzvRRd9UUkBFCS6NUsxCDBNOjsQ",
  RANGE_PRODUCTOS: "Productos!A:E",
  RANGE_PEDIDOS: "Pedidos!A:G",
  WHATSAPP: "59892308828"
};
